import 'package:dropdown_model_list/drop_down/model.dart';

DropListModel dropListModelCity = DropListModel([
    OptionItem(id: "1", title: "Abha"),
    OptionItem(id: "2", title: "Ad-Dilam"),
    OptionItem(id: "3", title: "Al-Abwa"),
    OptionItem(id: "4", title: "Al Artaweeiyah"),
    OptionItem(id: "5", title: "Al Bukayriyah"),
    OptionItem(id: "6", title: "Badr"),
    OptionItem(id: "7", title: "Baljurashi"),
    OptionItem(id: "8", title: "Bisha"),
    OptionItem(id: "9", title: "Bareq"),
    OptionItem(id: "10", title: "Buraydah"),
    OptionItem(id: "11", title: "Al Bahah"),
    OptionItem(id: "12", title: "Arar"),
    OptionItem(id: "13", title: "Dammam"),
    OptionItem(id: "14", title: "Dhahran"),
    OptionItem(id: "15", title: "Dhurma"),
    OptionItem(id: "16", title: "Dahaban"),
    OptionItem(id: "17", title: "Diriyah"),
    OptionItem(id: "18", title: "Duba"),
    OptionItem(id: "19", title: "Dumat Al-Jandal"),
    OptionItem(id: "20", title: "Dawadmi"),
    OptionItem(id: "21", title: "Farasan"),
    OptionItem(id: "22", title: "Gatgat"),
    OptionItem(id: "23", title: "Gerrha"),
    OptionItem(id: "24", title: "Ghawiyah"),
    OptionItem(id: "25", title: "Al-Gwei'iyyah"),
    OptionItem(id: "26", title: "Hautat Sudair"),
    OptionItem(id: "27", title: "Habaala"),
    OptionItem(id: "28", title: "Hajrah"),
    OptionItem(id: "29", title: "Haql"),
    OptionItem(id: "30", title: "Al-Hareeq"),
    OptionItem(id: "31", title: "Harmah"),
    OptionItem(id: "32", title: "Ha'il"),
    OptionItem(id: "33", title: "Hotat Bani Tamim"),
    OptionItem(id: "34", title: "Hofuf"),
    OptionItem(id: "35", title: "Huraymila"),
    OptionItem(id: "36", title: "Hafr Al-Batin"),
    OptionItem(id: "37", title: "Jabal Umm al Ru'us"),
    OptionItem(id: "38", title: "Jalajil"),
    OptionItem(id: "39", title: "Jeddah"),
    OptionItem(id: "40", title: "Jizan"),
    OptionItem(id: "41", title: "Jazan Economic City"),
    OptionItem(id: "42", title: "Jubail"),
    OptionItem(id: "43", title: "Al Jafr"),
    OptionItem(id: "44", title: "Khafji"),
    OptionItem(id: "45", title: "Khaybar"),
    OptionItem(id: "46", title: "King Abdullah Economic City"),
    OptionItem(id: "47", title: "Khamis Mushait"),
    OptionItem(id: "48", title: "Al-Saih"),
    OptionItem(id: "49", title: "Knowledge Economic City, Medina"),
    OptionItem(id: "50", title: "Khobar"),
    OptionItem(id: "51", title: "Al-Khutt"),
    OptionItem(id: "52", title: "Layla"),
    OptionItem(id: "53", title: "Lihyan"),
    OptionItem(id: "54", title: "Al Lith"),
    OptionItem(id: "55", title: "Al Majma'ah"),
    OptionItem(id: "56", title: "Mastoorah"),
    OptionItem(id: "57", title: "Al Mikhwah"),
    OptionItem(id: "58", title: "Al-Mubarraz"),
    OptionItem(id: "59", title: "Al Mawain"),
    OptionItem(id: "60", title: "Medina"),
    OptionItem(id: "61", title: "Mecca"),
    OptionItem(id: "62", title: "Muzahmiyya"),
    OptionItem(id: "63", title: "Najran"),
    OptionItem(id: "64", title: "Al-Namas"),
    OptionItem(id: "65", title: "Umluj"),
    OptionItem(id: "66", title: "Al-Omran"),
    OptionItem(id: "67", title: "Al-Oyoon"),
    OptionItem(id: "68", title: "Qadeimah"),
    OptionItem(id: "69", title: "Qatif"),
    OptionItem(id: "70", title: "Qaisumah"),
    OptionItem(id: "71", title: "Al Qadeeh"),
    OptionItem(id: "72", title: "Al Qunfudhah"),
    OptionItem(id: "73", title: "Qurayyat"),
    OptionItem(id: "74", title: "Rabigh"),
    OptionItem(id: "75", title: "Rafha"),
    OptionItem(id: "76", title: "Ar Rass"),
OptionItem(id: "77", title: "Ras Tanura"),
OptionItem(id: "78", title: "Rumah"),
OptionItem(id: "79", title: "Ranyah"),
OptionItem(id: "80", title: "Riyadh"),
OptionItem(id: "81", title: "Riyadh Al-Khabra"),
OptionItem(id: "82", title: "Rumailah"),
OptionItem(id: "83", title: "Sabt Al Alaya"),
OptionItem(id: "84", title: "Sarat Abidah"),
OptionItem(id: "85", title: "Saihat"),
OptionItem(id: "86", title: "Safwa city"),
OptionItem(id: "87", title: "Sakakah"),
OptionItem(id: "88", title: "Sharurah"),
OptionItem(id: "89", title: "Shaqra"),
OptionItem(id: "90", title: "Shaybah"),
OptionItem(id: "91", title: "As Sulayyil"),
OptionItem(id: "92", title: "Taif"),
OptionItem(id: "93", title: "Tabuk"),
OptionItem(id: "94", title: "Tanomah"),
OptionItem(id: "95", title: "Tarout"),
OptionItem(id: "96", title: "Tayma"),
OptionItem(id: "97", title: "Thadiq"),
OptionItem(id: "98", title: "Thuwal"),
OptionItem(id: "99", title: "Thuqbah"),
OptionItem(id: "100", title: "Turaif"),
OptionItem(id: "101", title: "Tabarjal"),
OptionItem(id: "102", title: "Udhailiyah"),
OptionItem(id: "103", title: "Al-'Ula"),
OptionItem(id: "104", title: "Um Al-Sahek"),
OptionItem(id: "105", title: "Unaizah"),
OptionItem(id: "106", title: "Uqair"),
OptionItem(id: "107", title: "Uyayna"),
OptionItem(id: "108", title: "Uyun AlJiwa"),
OptionItem(id: "109", title: "Wadi Al-Dawasir"),
OptionItem(id: "110", title: "Al Wajh"),
OptionItem(id: "111", title: "Yanbu"),
OptionItem(id: "112", title: "Az Zaimah"),
OptionItem(id: "113", title: "Zulfi"),
]);
OptionItem optionItemSelected = OptionItem(title: "Select City");
 






 DropListModel dropListModelGender = DropListModel([
    OptionItem(id: "1", title: "Male"),
    OptionItem(id: "2", title: "Female"),
    OptionItem(id: "3", title: "prefer not to say")
    
  ]);
  OptionItem optionItemSelectedgender = OptionItem(title: "Select gender");